version: '2'
services:
    restapi:
        container_name: api_demo
        build: .
        restart: always
        command: uwsgi --ini uwsgi.ini
        ports:
            - "8010:8010"
        volumes:
            - ./app:/srv/www/apidemo
        links:
            - db_postgresql

    db_postgresql:
        build: ./db_yachay
        container_name: yachay_postgres
        environment:
            POSTGRES_PASSWORD: "123456"
