"""Segunda

Revision ID: 5b84f9101cc7
Revises: 07bc4f64a2de
Create Date: 2016-08-03 20:59:07.301401

"""

# revision identifiers, used by Alembic.
revision = '5b84f9101cc7'
down_revision = '07bc4f64a2de'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('bio', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'bio')
    ### end Alembic commands ###
