"""Tercera - Alter Table

Revision ID: 64cb6b328ac5
Revises: 5b84f9101cc7
Create Date: 2016-08-03 22:13:28.420511

"""

# revision identifiers, used by Alembic.
revision = '64cb6b328ac5'
down_revision = '5b84f9101cc7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    
    # op.create_table('UserNew',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('guid', sa.String(), nullable=True),
    # sa.Column('email', sa.String(), nullable=True),
    # sa.Column('password', sa.String(), nullable=True),
    # sa.Column('bio', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('guid')
    # )
    # op.drop_table('User')

    op.rename_table('User', 'UserNew')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    # op.create_table('User',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"User_id_seq"\'::regclass)'), nullable=False),
    # sa.Column('guid', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=u'User_pkey'),
    # sa.UniqueConstraint('email', name=u'User_email_key'),
    # sa.UniqueConstraint('guid', name=u'User_guid_key')
    # )
    # op.drop_table('UserNew')

    op.rename_table('UserNew', 'User')

    ### end Alembic commands ###
