"""Cuarta - Alter Column

Revision ID: 6a7dae755e04
Revises: 64cb6b328ac5
Create Date: 2016-08-03 22:23:50.141544

"""

# revision identifiers, used by Alembic.
revision = '6a7dae755e04'
down_revision = '64cb6b328ac5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    
    # op.add_column('UserNew', sa.Column('biography', sa.String(), nullable=True))
    # op.drop_column('UserNew', 'bio')

    op.execute('ALTER TABLE public."UserNew" RENAME COLUMN bio TO biography')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    
    # op.add_column('UserNew', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.drop_column('UserNew', 'biography')

    op.execute('ALTER TABLE public."UserNew" RENAME COLUMN biography TO bio')

    ### end Alembic commands ###
