"""quinta - no quotes

Revision ID: 716ac13c9103
Revises: 6a7dae755e04
Create Date: 2016-08-04 16:28:46.849238

"""

# revision identifiers, used by Alembic.
revision = '716ac13c9103'
down_revision = '6a7dae755e04'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('guid', sa.String(), nullable=True),
    # sa.Column('email', sa.String(), nullable=True),
    # sa.Column('password', sa.String(), nullable=True),
    # sa.Column('biography', sa.String(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('guid')
    # )
    # op.drop_table('UserNew')

    op.execute('ALTER TABLE public."UserNew" RENAME TO UserNew')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('UserNew',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"User_id_seq"\'::regclass)'), nullable=False),
    # sa.Column('guid', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('biography', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=u'User_pkey'),
    # sa.UniqueConstraint('email', name=u'User_email_key'),
    # sa.UniqueConstraint('guid', name=u'User_guid_key')
    # )
    # op.drop_table('user')

    op.execute('ALTER TABLE UserNew RENAME TO public."UserNew"')

    ### end Alembic commands ###
