"""pechy

Revision ID: 8bfe79b6fcb0
Revises: db09cc0f11c0
Create Date: 2016-08-03 15:51:43.513136

"""

# revision identifiers, used by Alembic.
revision = '8bfe79b6fcb0'
down_revision = 'db09cc0f11c0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('bio', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'bio')
    ### end Alembic commands ###
